app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    # url(r'^/', views.login, name='login'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.user_logout, name='logout'),
    url(r'^domaininfo/', views.domain_info, name='domain_info'),
    url(r'^adddomain/', views.add_domain, name='adddomain'),
    url(r'^search/', views.search, name='search'),
    url(r'^delete/', views.delete_date, name='delete'),
    url(r'^palcesort/', views.place_sort, name='place_sort'),
    url(r'^typesort/', views.type_sort, name='type_sort'),
    url(r'^label/', views.label_data, name='label'),
    url(r'^sort291/', views.sort_291, name='sort_291'),
    url(r'^sort646/', views.sort_646, name='sort_646'),
    url(r'^sortjj/', views.sort_jj, name='sort_jj'),
    url(r'^sortty1/', views.sort_ty1, name='sort_ty1'),
    url(r'^sortty2/', views.sort_ty2, name='sort_ty2'),
    url(r'^sorttc/', views.sort_tc, name='sort_tc'),
    url(r'^sorttcgj/', views.sort_tcgj, name='sort_tcgj'),
    url(r'^sorttcss/', views.sort_tcss, name='sort_tcss'),
    url(r'^sortycgj/', views.sort_ycgj, name='sort_ycgj'),
    url(r'^sortscgj/', views.sort_scgj, name='sort_scgj'),
    url(r'^sortqcgj/', views.sort_qcgj, name='sort_qcgj'),
    url(r'^sortmcgj/', views.sort_mcgj, name='sort_mcgj'),
    url(r'^sorttc6/', views.sort_tc6, name='sort_tc6'),
    url(r'^sortmd/', views.sort_master_domain, name='sort_master_domain'),
    url(r'^sortldy/', views.sort_ldy, name='sort_ldy'),
    url(r'^sortqd/', views.sort_qd, name='sort_qd'),
    url(r'^labeldreamin/', views.label_dreamin, name='label_dreamin'),
    url(r'^labelremain/', views.label_remain, name='label_remain'),
    url(r'^labelwxwaf/', views.label_wxwaf, name='label_wxwaf'),
    url(r'^labelwaf/', views.label_waf, name='label_waf'),
    url(r'^labelbeian/', views.label_beian, name='label_beian'),
    url(r'^update/', views.update, name='update'),
    url(r'^addinbulk/', views.add_in_bulk, name='add_in_bulk'),
]

domain/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('app.urls', namespace='app'))
]

templates/add_in_bulk.html
{% extends 'base_domain.html' %}
{% load staticfiles %}
{% block header %}
    {{ block.super }}
{% endblock %}
{% block content %}
    <div class="ui center aligned grid" style="margin-top: 60px">
        <div class="ui six wide column">
            <div class="ui brown inverted segment"></div>
            <div class="ui form">
                <div class="ui message">
                    <div class="header">批量添加域名</div>
                    <ul class="list">
                        <li>请遵循以下格式，一行一个</li>
                        <li>baidu.com|xxx|主域名</li>
                    </ul>
                </div>
                <form action="{% url 'app:add_in_bulk' %}" method="post" class="ui segment form">
                    {% csrf_token %}
                    <div class="field">
                        <textarea name="domain_data" placeholder="请输入域名，每行一个"></textarea>
                        {% if d_count >= 7 %}
                            <button class="ui fluid large teal button">提交</button>
                        {% else %}
                            <div class="ui form error">
                                <div class="ui error message">
                                    <div class="header">域名格式输入错误</div>
                                </div>
                                <button class="ui fluid large teal button">提交</button>
                            </div>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}

{% endblock %}

templates/add_page_jump.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>错误信息</title>
</head>
<body>
<p>
<h1>{{ error }}
    <span id="sp">5</span>
    秒跳转到批量添加域名界面...
</h1>
</p>
<script>
    onload = function () {
        setInterval(go, 1000)
    };
    var x = 4;

    function go() {

        if (x >= 0) {
            document.getElementById("sp").innerText = x;
        } else {
            location.href = "/addinbulk/";
        }
        x--;
    }
</script>
</body>
</html>

templates/adddomain.html
{% extends 'base_domain.html' %}
{% load staticfiles %}

{% block header %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <div class="ui center aligned grid" style="margin-top: 60px">
        <div class="ui six wide column">
            <h2 class="ui teal image header">
                <div class="content">
                    添加域名
                </div>
            </h2>
            <div class="ui segment">
                <div class="ui content">
                    <form action="{% url 'app:adddomain' %}" method="post" class="ui segment form">
                        {% csrf_token %}
                        <div class="image content">
                            <div class="ui fluid input">
                                {{ form.Form_url }}
                                {{ error.Form_url }}
                            </div>
                            <br>
                            {{ form.Form_type }}
                            <br>
                            {{ form.Form_dtype }} {{ error.Form_dtype }}
                            <br>
                            <button class="ui fluid large teal button">提交</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}

{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="{% static 'img/icon.png' %}">
    <title>{{ title }}</title>
    {% block ext_css %}
        <link rel="stylesheet" href="{% static 'css/semantic.css' %}">
    {% endblock %}
</head>
<body>
{% block header %}

{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}

{% block ext_js %}
    <script type="text/javascript" src="{% static 'js/semantic.js' %}"></script>
{% endblock %}
</body>
</html>

templates/base_domain.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block header %}
    {{ block.super }}
    <nav class="ui inverted attached segment my-padded-tb-mini">
        <div class="ui container">
            <div class="ui inverted secondary stackable menu">
                <h2 class="ui teal header item">
                    <img class="logo" src="/static/img/logo.jpg">
                    域名管理中心
                </h2>
                <a href="{% url 'app:domain_info' %}" class="item"><i class="home icon"></i>首页</a>
                <a href="{% url 'app:place_sort' %}" class="item"><i class="idea icon"></i>平台分类</a>
                <a href="{% url 'app:type_sort' %}" class="item"><i class="idea icon"></i>类型分类</a>
                <a href="{% url 'app:label' %}" class="item"><i class="tags icon"></i>标签</a>
                <div class="right item">
                    <div class="ui icon inverted transparent input">
                        <form class="ui form" style="display:flex;align-item:center;" method="post"
                              action="{% url 'app:search' %}">
                            {% csrf_token %}
                            <input type="text" name="sear" placeholder="搜索">
                            <button class="button" type="submit"><i class="search link icon"></i></button>
                        </form>
                    </div>
                </div>
                <div class="right my-item my-mobile-hide menu my-margin-top-small">
                    <div class="ui dropdown inline item">
                        <div class="text">
                            <img class="ui avatar image" src="/static/img/abu.jpg">阿布
                        </div>
                        <i class="dropdown icon"></i>
                        <div class="right item">
                            <a href="{% url 'app:logout' %}" class="item">注销</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <div class="ui inverted attached pointing menu">
        <div class="ui container">
            <div class="right menu">
                <div class="ui simple dropdown item">
                    添加域名
                    <i class="dropdown icon"></i>
                    <div class="menu">
                        <div class="item">
                            <a href="{% url 'app:adddomain' %}" style="color: #171616" class="item" rel="nofollow"><i class="add icon"></i>添加单个域名</a>
                        </div>
                        <div class="item">
                            <a href="{% url 'app:add_in_bulk' %}" style="color: #171616" class="item"><i class="add icon"></i>添加多个域名</a>
                        </div>
                    </div>
                </div>
                <a href="{% url 'app:domain_info' %}" class="active teal item">列表</a>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    <div style="text-align: right;padding-right: 50px;">
        <tr>
            <th colspan="6">
                {% if page_object.has_previous %}
                    <div class="ui teal pagination menu">
                        <a href="#" class="item">上一页</a>
                    </div>
                {% else %}
                    <div class="ui teal pagination menu">
                        <a class="item">上一页</a>
                    </div>
                {% endif %}
            </th>
        </tr>
        <div class="ui pagination menu">
            {% for page_index in page_range %}
                {% ifequal page_index page_object.number %}
                    <div class="active item"><a
                            href="{% url 'app:domain_info' %}?page={{ page_index }}">{{ page_index }}</a></div>
                {% else %}
                    <div class="item"><a
                            href="{% url 'app:domain_info' %}?page={{ page_index }}">{{ page_index }}</a>
                    </div>
                {% endifequal %}
            {% endfor %}
        </div>
        <!-- 翻页按钮 -->
        <tr>
            <th colspan="6">
                {% if page_object.has_next %}
                    <div class="ui teal pagination menu">
                        <a href="#" class="item">下一页</a>
                    </div>
                {% else %}
                    <div class="ui teal pagination menu">
                        <a class="item">下一页</a>
                    </div>
                {% endif %}
            </th>
        </tr>
    </div>
{% endblock %}

templates/base_login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block ext_css %}
    {{ block.super }}
{% endblock %}
{% block header %}
    <header></header>
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/md5.js' %}"></script>
{% endblock %}

templates/domainmanager.html
{% extends 'base_domain.html' %}
{% load staticfiles %}
{% block header %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <table class="ui celled table">
        <thead>
        <tr>
            <th></th>
            <th>域名</th>
            <th>平台</th>
            <th>域名类型</th>
            <th>证书开始时间</th>
            <th>证书到期时间</th>
            <th>证书剩余时间</th>
            <th>域名DNS记录</th>
            <th>域名A记录</th>
            <th>域名到期时间</th>
            <th>最后更新时间</th>
            <th>是否备案</th>
            <th>是否被微信拦截</th>
            <th>是否被墙</th>
            <th>操作</th>
        </tr>
        </thead>
        {% for cert in page_object.object_list %}
            <tbody>
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ cert.name }}</td>
                <td>{{ cert.type }}</td>
                <td>{{ cert.dtype }}</td>
                <td>{{ cert.notbefore }}</td>
                <td>{{ cert.notafter }}</td>
                {% if cert.remain_days <= 7 %}
                    <td style="color: red">即将到期{{ cert.remain_days }}天</td>
                {% else %}
                    <td>{{ cert.remain_days }}天</td>
                {% endif %}
                <td>{{ cert.dnsinfo }}</td>
                <td>{{ cert.a_notes }}</td>
                {% if cert.dreamin_days <= 7 %}
                    <td style="color: red">即将到期{{ cert.dreamin_days }}天</td>
                {% else %}
                    <td>{{ cert.dreamin_days }}天</td>
                {% endif %}
                <td>{{ cert.last_time }}</td>
                {% if cert.beian == True %}
                    <td style="color: navy">已备案</td>
                {% else %}
                    <td style="color: #3c5876">无备案</td>
                {% endif %}
                {% if cert.wxwaf == True %}
                    <td style="color: red">微信拦截</td>
                {% else %}
                    <td>正常</td>
                {% endif %}
                {% if cert.waf == True %}
                    <td style="color: red">域名被墙</td>
                {% else %}
                    <td>正常</td>
                {% endif %}
                <td>
                    <a name="update" href="javascript:" onclick="up_data(this, {{ cert.id }})"
                       class="ui mini teal button">更新</a>
                    <a name="delete" href="javascript:" onclick="del_data(this, {{ cert.id }})"
                       class="ui mini red button">删除</a>
                </td>
            </tr>
            </tbody>
        {% endfor %}
    </table>
{% endblock %}

{% block ext_js %}
    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.js"></script>
    <script src="https://cdn.bootcss.com/layer/2.1/layer.js"></script>
    <script type="text/javascript">
        function del_data(the, cert_id) {
            var cert_name = $(the).parents("tr").children("td").eq(1).text();
            layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["400px", "200px"],
                title: "删除域名",
                content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除' + cert_name + '</p></div>',
                btn: ['确定', '取消'],
                yes: function () {

                    $.ajax({
                        url: '{% url "app:delete" %}',
                        type: "POST",
                        data: {"cert_id": cert_id},
                        success: function (e) {
                            if (e == "1") {
                                parent.location.reload();
                                layer.msg("删除成功");
                            } else {
                                layer.msg("删除失败");
                            }

                        },
                    })
                },
            });
        }

        function up_data(the, cert_id) {
            var cert_name = $(the).parents("tr").children("td").eq(1).text();
            layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["400px", "200px"],
                title: "更新域名",
                content: '<div class="text-center" style="margin-top:20px"><p>是否确定更新' + cert_name + '</p></div>',
                btn: ['确定', '取消'],
                yes: function () {

                    $.ajax({
                        url: '{% url "app:update" %}',
                        type: "POST",
                        data: {"cert_id": cert_id},
                        success: function (e) {
                            if (e == "1") {
                                parent.location.reload();
                                layer.msg("更新成功");
                            } else {
                                layer.msg("更新失败");
                            }

                        },
                    })
                },
            });
        }
    </script>
{% endblock %}

templates/label.html
{% extends 'base_domain.html' %}
{% load staticfiles %}
{% block header %}
    {{ block.super }}
{% endblock %}
{% block content %}
    <div class="ui segment my-margin-top-large">
        <div class="ui secondary segment">
            <div class="ui two column grid">
                <div class="column">
                    <i class="tags icon"></i>标签
                </div>
            </div>
        </div>
        <div class="ui teal segment">
            <a href="{% url 'app:label_dreamin' %}" class="ui teal basic left pointing label my-margin-tb-tiny">
                将到期域名
                <div class="detail">{{ ldreamin }}</div>
            </a>
            <a href="{% url 'app:label_remain' %}" class="ui teal basic left pointing label my-margin-tb-tiny">
                证书将到期
                <div class="detail">{{ lremain }}</div>
            </a>
            <a href="{% url 'app:label_wxwaf' %}" class="ui teal basic left pointing label my-margin-tb-tiny">
                被微信拦截
                <div class="detail">{{ lwxwaf }}</div>
            </a>
            <a href="{% url 'app:label_waf' %}" class="ui teal basic left pointing label my-margin-tb-tiny">
                被墙
                <div class="detail">{{ lwaf }}</div>
            </a>
            <a href="{% url 'app:label_beian' %}" class="ui teal basic left pointing label my-margin-tb-tiny">
                掉备案
                <div class="detail">{{ lbeian }}</div>
            </a>
        </div>
    </div>
    <div class="ui segment my-margin-top-large">
        <div class="ui secondary segment">
            <i class="bookmark icon"></i>改编不是乱编，戏说不是胡说
        </div>
        <div class="ui segment">
            <a href="http://baidu.com" class="my-black my-text-thin">niaho</a>
        </div>
        <div class="ui segment">
            <a href="#" class="my-black my-text-thin">nihao</a>
        </div>
        <div class="ui segment">
            <a href="#" class="my-black my-text-thin">nihao</a>
        </div>
        <div class="ui segment">
            <a href="#" class="my-black my-text-thin">阿布</a>
        </div>
    </div>
{% endblock %}

{% block ext_js %}

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block ext_css %}
    {{ block.super }}
{% endblock %}
{% block header %}
    <header></header>
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/login.js' %}"></script>
{% endblock %}

{% block content %}
    <body style="background-color: rgb(230,230,230)">
    <div class="ui center aligned grid" style="margin-top: 200px">
        <div class="ui six wide column">
            <h1 class="ui teal image header">
                <img src="/static/img/login.jpg" class="image">
                <div class="content">
                    域名管理中心
                </div>
            </h1>
            <div class="ui segment">
                <div class="ui content">
                    <form class="ui form" method="post" action="{% url 'app:login' %}" onsubmit="return parse_data()">
                        {% csrf_token %}
                        <div class="field">
                            <div class="ui left icon input">
                                <i class="user icon"></i>
                                <input type="text" name="username" class="form-control" id="username_input"
                                       placeholder="用户名"><br>
                            </div>
                        </div>
                        <div class="field">
                            <div class="ui left icon input">
                                <i class="lock icon"></i>
                                <input type="password" name="password" class="form-control" id="password_input"
                                       placeholder="密码"><br>
                            </div>
                        </div>
                        {#                        <div class="field">#}
                        {#                            <div class="ui left icon input">#}
                        {#                                <i class="hand point right icon"></i>#}
                        {#                                <input type="password" name="password" class="form-control" id="password_input"#}
                        {#                                       placeholder="验证码"><br>#}
                        {#                            </div>#}
                        {#                        </div>#}
                        <li style="color: red">{{ error }}<br></li>
                        <button class="ui fluid large teal button" onclick="login()">登录</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </body>
{% endblock %}

{% block footer %}
    {{ block.super }}
{% endblock %}

templates/page_jump.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>IP白名单限制</title>
</head>
<body>
<p>
<h1>IP白名单限制！还有
    <span id="sp">5</span>
    秒跳转到登录页面...
</h1>
</p>
<script>
    onload = function () {
        setInterval(go, 1000)
    };
    var x = 4;

    function go() {

        if (x >= 0) {
            document.getElementById("sp").innerText = x;
        } else {
            location.href = "/login/";
        }
        x--;
    }
</script>
</body>
</html>

templates/page_jump_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>错误信息</title>
</head>
<body>
<p>
<h1>{{ error }}
    <span id="sp">5</span>
    秒跳转到添加域名界面...
</h1>
</p>
<script>
    onload = function () {
        setInterval(go, 1000)
    };
    var x = 4;

    function go() {

        if (x >= 0) {
            document.getElementById("sp").innerText = x;
        } else {
            location.href = "/adddomain/";
        }
        x--;
    }
</script>
</body>
</html>

templates/place_sort.html
{% extends 'base_domain.html' %}
{% load staticfiles %}
{% block header %}
    {{ block.super }}
{% endblock %}
{% block content %}
    <div class="ui segment">
        <div class="ui secondary segment">
            <div class="ui two column grid">
                <div class="column">
                    <i class="idea icon"></i>平台分类
                </div>
            </div>
        </div>
        <div class="ui teal segment">
            <div class="ui fluid vertical menu">
                <a href="{% url 'app:sort_291' %}" class="item">
                    xx
                    <div class="ui teal basic left pointing label">{{ certs291 }}</div>
                </a>
                <a href="{% url 'app:sort_646' %}" class="item">
                    xx
                    <div class="ui teal basic left pointing label">{{ certs646 }}</div>
                </a>
                <a href="{% url 'app:sort_ty1' %}" class="item">
                    xx
                    <div class="ui teal basic left pointing label">{{ certsty1 }}</div>
                </a>
                <a href="{% url 'app:sort_ty2' %}" class="item">
                    xx
                    <div class="ui teal basic left pointing label">{{ certsty2 }}</div>
                </a>
                <a href="{% url 'app:sort_tc' %}" class="item">
                    xx
                    <div class="ui teal basic left pointing label">{{ certstc }}</div>
                </a>
                <a href="{% url 'app:sort_jj' %}" class="item">
                    JJ
                    <div class="ui teal basic left pointing label">{{ certsjj }}</div>
                </a>
                <a href="{% url 'app:sort_tcgj' %}" class="item">
                    xx
                    <div class="ui teal basic left pointing label">{{ certstcgj }}</div>
                </a>
                <a href="{% url 'app:sort_tcss' %}" class="item">
                    xx
                    <div class="ui teal basic left pointing label">{{ certstcss }}</div>
                </a>
                <a href="{% url 'app:sort_ycgj' %}" class="item">
                    xx
                    <div class="ui teal basic left pointing label">{{ certsycgj }}</div>
                </a>
                <a href="{% url 'app:sort_scgj' %}" class="item">
                    xx
                    <div class="ui teal basic left pointing label">{{ certsscgj }}</div>
                </a>
                <a href="{% url 'app:sort_qcgj' %}" class="item">
                    xx
                    <div class="ui teal basic left pointing label">{{ certsqcgj }}</div>
                </a>
                <a href="{% url 'app:sort_mcgj' %}" class="item">
                    xx
                    <div class="ui teal basic left pointing label">{{ certsmcgj }}</div>
                </a>
                <a href="{% url 'app:sort_tc6' %}" class="item">
                    xx
                    <div class="ui teal basic left pointing label">{{ certstc6 }}</div>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

{% block ext_js %}

{% endblock %}

templates/search.html
{% extends 'base_domain.html' %}
{% load staticfiles %}
{% block header %}
    {{ block.super }}
{% endblock %}
{% block content %}
    <table class="ui celled table">
        <thead>
        <tr>
            <th></th>
            <th>域名</th>
            <th>平台</th>
            <th>域名类型</th>
            <th>证书开始时间</th>
            <th>证书到期时间</th>
            <th>证书剩余时间</th>
            <th>域名DNS记录</th>
            <th>域名A记录</th>
            <th>域名到期时间</th>
            <th>最后更新时间</th>
            <th>是否备案</th>
            <th>是否被微信拦截</th>
            <th>是否被墙</th>
            <th>操作</th>
        </tr>
        </thead>
        {% for type in stype %}
            <tbody>
            <tr>
                <td>{{ forloop.counter }}</td>
                <td style="color: red">{{ type.name }}</td>
                <td>{{ type.type }}</td>
                <th>{{ type.dtype }}</th>
                <td>{{ type.notbefore }}</td>
                <td>{{ type.notafter }}</td>
                {% if type.remain_days <= 7 %}
                    <td style="color: red">即将到期{{ type.remain_days }}天</td>
                {% else %}
                    <td>{{ type.remain_days }}天</td>
                {% endif %}
                <td>{{ type.dnsinfo }}</td>
                <td>{{ type.a_notes }}</td>
                {% if type.dreamin_days <= 7 %}
                    <td style="color: red">即将到期{{ type.dreamin_days }}天</td>
                {% else %}
                    <td>{{ type.dreamin_days }}天</td>
                {% endif %}
                <td>{{ type.last_time }}</td>
                {% if type.beian == True %}
                    <td style="color: navy">已备案</td>
                {% else %}
                    <td style="color: #3c5876">无备案</td>
                {% endif %}
                {% if type.wxwaf == True %}
                    <td style="color: red">微信拦截</td>
                {% else %}
                    <td>正常</td>
                {% endif %}
                {% if type.waf == True %}
                    <td style="color: red">域名被墙</td>
                {% else %}
                    <td>正常</td>
                {% endif %}
                <td>
                    <a name="update" href="javascript:" onclick="up_data(this, {{ cert.id }})"
                       class="ui mini teal button">更新</a>
                    <div class="right item">
                        <a name="delete" href="javascript:" onclick="del_data(this, {{ type.id }})"
                           class="ui mini red button">删除</a>
                    </div>
                </td>
            </tr>
            </tbody>
        {% endfor %}
    </table>
{% endblock %}

{% block ext_js %}
    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.js"></script>
    <script src="https://cdn.bootcss.com/layer/2.1/layer.js"></script>
    <script type="text/javascript">
        function del_data(the, cert_id) {
            var cert_name = $(the).parents("tr").children("td").eq(1).text();
            layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["400px", "200px"],
                title: "删除域名",
                content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除' + cert_name + '</p></div>',
                btn: ['确定', '取消'],
                yes: function () {
                    $.ajax({
                        url: '{% url "app:delete" %}',
                        type: "POST",
                        data: {"cert_id": cert_id},
                        success: function (e) {
                            if (e == "1") {
                                parent.location.reload();
                                layer.msg("删除成功");
                            } else {
                                layer.msg("删除失败");
                            }

                        },
                    })
                },
            });
        }

        function up_data(the, cert_id) {
            var cert_name = $(the).parents("tr").children("td").eq(1).text();
            layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["400px", "200px"],
                title: "更新域名",
                content: '<div class="text-center" style="margin-top:20px"><p>是否确定更新' + cert_name + '</p></div>',
                btn: ['确定', '取消'],
                yes: function () {

                    $.ajax({
                        url: '{% url "app:update" %}',
                        type: "POST",
                        data: {"cert_id": cert_id},
                        success: function (e) {
                            if (e == "1") {
                                parent.location.reload();
                                layer.msg("更新成功");
                            } else {
                                layer.msg("更新失败");
                            }

                        },
                    })
                },
            });
        }
    </script>
{% endblock %}

templates/type_sort.html
{% extends 'base_domain.html' %}
{% load staticfiles %}

{% block header %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <div class="ui segment">
        <div class="ui secondary segment">
            <div class="ui two column grid">
                <div class="column">
                    <i class="idea icon"></i>类型分类
                </div>
            </div>
        </div>
        <div class="ui teal segment">
            <div class="ui fluid vertical menu">
                <a href="{% url 'app:sort_master_domain' %}" class="item">
                    主域名
                    <div class="ui teal basic left pointing label">{{ certs_zym }}</div>
                </a>
                <a href="{% url 'app:sort_ldy' %}" class="item">
                    落地页
                    <div class="ui teal basic left pointing label">{{ certs_ldy }}</div>
                </a>
                <a href="{% url 'app:sort_qd' %}" class="item">
                    渠道
                    <div class="ui teal basic left pointing label">{{ certs_qudao }}</div>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

{% block ext_js %}

{% endblock %}